services:
  room-renting-db:
    image: postgres:16.3-bullseye
    container_name: room_renting_db
    ports:
      - 4441:5432
    environment:
      POSTGRES_PASSWORD: roomrenting@2024
      POSTGRES_USER: room
      POSTGRES_DB: room_renting_db
    volumes:
      - room-vol:/var/lib/postgresql/data
volumes:
  room-vol:

